version: '2'
services:
    web:
        image: nginx:1.13-alpine
        ports:
            - 8880:80
        volumes:
            - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/web
        links:
            - php
    php:
        image: php:7.2-rc-fpm-alpine3.6
        volumes:
          - ./:/web
        working_dir: /web

    redis:
        restart: always
        image: redis:latest
        ports:
          - 6379:6379
